// This file was generated by Prisma, and assumes you have installed following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || 'mongodb://localhost:27017/applycopilot',
  },
});
